# Importing numpy

In [1]:
import numpy as np

# Array Attributes

In [2]:
a = np.array([1, 2, 3]) #1D array/ vector

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.ndim

1

In [7]:
b = np.array([[1, 2, 3],
              [4, 5.0, 6]]) #2d array

In [8]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
type(b)

numpy.ndarray

In [10]:
a.shape

(3,)

In [11]:
b.ndim

2

In [12]:
c = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [13]:
c.shape

(3, 3)

In [14]:
a.dtype, b.dtype, c.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
a.size, b.size, c.size

(3, 6, 9)

In [16]:
a.nbytes, b.nbytes, c.nbytes

(12, 48, 36)

# Array Creation

In [17]:
array1 = np.array([1, 2, 3], dtype = 'int')

In [18]:
array1

array([1, 2, 3])

In [19]:
zeros = np.zeros((3,3), dtype = 'int')

In [20]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
ones = np.ones((3,3), dtype = 'int')

In [22]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
full = np.full((2,3), 10)

In [24]:
full

array([[10, 10, 10],
       [10, 10, 10]])

In [25]:
identity = np.identity(3) #dtype default

In [26]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
eye = np.eye(3, 3, 1)

In [28]:
eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [29]:
arange = np.arange(1, 10, 2)

In [30]:
arange

array([1, 3, 5, 7, 9])

In [31]:
linspace = np.linspace(1, 10, dtype = 'int')

In [32]:
linspace

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [33]:
empty = np.empty((1, 5))

In [34]:
empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 5.63234836e-322]])

In [35]:
for i in range(5):
    empty[:, i] = i
empty

array([[0., 1., 2., 3., 4.]])

# Array Indexing and Slicing

# Indexing

In [36]:
arr1 = np.array([1, 2, 3, 4, 5])

In [37]:
print(arr1)

[1 2 3 4 5]


In [38]:
arr1[0]

1

In [39]:
arr1[4]

5

In [40]:
arr1[-1]

5

In [41]:
arr1[-3]

3

In [42]:
arr2 = np.random.randint(1, 10, size = (3, 3), dtype = 'int')

In [43]:
print(arr2)

[[2 8 4]
 [8 3 5]
 [9 3 7]]


In [44]:
arr2[0][0]

2

In [45]:
arr2[1, 1]

3

In [46]:
arr3 = np.random.randint(1, 100, size = (3 ,3, 3), dtype = 'int')

In [47]:
print(arr3)

[[[65 11 44]
  [55  4 29]
  [40 81  7]]

 [[85 39 62]
  [99 29 89]
  [86 12 89]]

 [[58 44 69]
  [81 30 84]
  [27 33 50]]]


In [48]:
arr3[0, 0, 1]

11

In [49]:
arr3[2][0][1]

44

In [50]:
arr3[2, 2, 2]

50

# Slicing

In [51]:
print(arr1)

[1 2 3 4 5]


In [52]:
print(arr1[0 : 3])

[1 2 3]


In [53]:
print(arr1[2 : ])

[3 4 5]


In [54]:
print(arr2)

[[2 8 4]
 [8 3 5]
 [9 3 7]]


In [55]:
print(arr2[0:2, 0:2])

[[2 8]
 [8 3]]


In [56]:
print(arr2[1: , 1:])

[[3 5]
 [3 7]]


# Manipilating array shapes
1. Reshape()
2. Resize()
3. Flatten()
4. Revel()
5. Defining array shape

### Reshape()

In [57]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])

In [58]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
a.shape

(2, 3)

In [60]:
a_reshape = np.reshape(a, (3, 2))

In [61]:
a_reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
a_reshape.shape

(3, 2)

### Resize() 

In [63]:
a_resize = np.resize(a, (4, 3))

In [64]:
a_resize

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [65]:
a_resize2 = np.resize(a, (3, 2))

In [66]:
a_resize2

array([[1, 2],
       [3, 4],
       [5, 6]])

### Ravel()

In [67]:
a = np.random.randint(1, 100, (2, 3)) #Return a view of the array

In [68]:
a

array([[55, 67, 63],
       [78, 13, 23]])

In [69]:
a_raveled = np.ravel(a)

In [70]:
print(a_raveled)

[55 67 63 78 13 23]


In [71]:
a_raveled.shape

(6,)

In [72]:
a_raveled[0] = 0

In [73]:
a_raveled

array([ 0, 67, 63, 78, 13, 23])

In [74]:
a

array([[ 0, 67, 63],
       [78, 13, 23]])

### Flatten() 

In [75]:
a_flatten = a.flatten() #Return a copy of the array, always allocate a new memory.

In [76]:
a_flatten

array([ 0, 67, 63, 78, 13, 23])

In [77]:
a_flatten[0] = 100

In [78]:
a_flatten

array([100,  67,  63,  78,  13,  23])

In [79]:
a

array([[ 0, 67, 63],
       [78, 13, 23]])

### Defining an array shape 

In [80]:
a

array([[ 0, 67, 63],
       [78, 13, 23]])

In [81]:
a.shape

(2, 3)

In [82]:
a.shape = (3, 2)

In [83]:
a

array([[ 0, 67],
       [63, 78],
       [13, 23]])

# Stacking 

#### Horizantal stacking

In [84]:
a

array([[ 0, 67],
       [63, 78],
       [13, 23]])

In [85]:
a = np.arange(1, 10).reshape(3, 3)

In [86]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
b = a * 2

In [88]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [89]:
np.hstack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [90]:
np.column_stack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

#### Vertical stacking

In [91]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [92]:
np.row_stack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

#### Depth stack

In [93]:
np.dstack((a, b))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])